values = input("Input some comma seprated numbers : ")
list = values.split(",")
tuple = tuple(list)
print('List : ',list)
print('Tuple : ',tuple)

values = input( 'numbers :' )
list = values.split(',')
tuple = tuple(list)
print = ( ' list : ',list)
print = ( ' tuple : ',tuple)